/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecipesIndexRouteImport } from './routes/recipes.index'
import { Route as ProfileIndexRouteImport } from './routes/profile.index'
import { Route as LogsIndexRouteImport } from './routes/logs.index'
import { Route as CookbooksIndexRouteImport } from './routes/cookbooks.index'
import { Route as RecipesNewRouteImport } from './routes/recipes.new'
import { Route as RecipesIdRouteImport } from './routes/recipes.$id'
import { Route as ProfileEditRouteImport } from './routes/profile.edit'
import { Route as ProfileIdRouteImport } from './routes/profile.$id'
import { Route as LogsIdRouteImport } from './routes/logs.$id'
import { Route as CookbooksNewRouteImport } from './routes/cookbooks.new'
import { Route as CookbooksIdRouteImport } from './routes/cookbooks.$id'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as AuthSigninRouteImport } from './routes/auth.signin'
import { Route as RecipesIdIndexRouteImport } from './routes/recipes.$id.index'
import { Route as CookbooksIdIndexRouteImport } from './routes/cookbooks.$id.index'
import { Route as RecipesIdEditRouteImport } from './routes/recipes.$id.edit'
import { Route as CookbooksIdEditRouteImport } from './routes/cookbooks.$id.edit'

const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesIndexRoute = RecipesIndexRouteImport.update({
  id: '/recipes/',
  path: '/recipes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsIndexRoute = LogsIndexRouteImport.update({
  id: '/logs/',
  path: '/logs/',
  getParentRoute: () => rootRouteImport,
} as any)
const CookbooksIndexRoute = CookbooksIndexRouteImport.update({
  id: '/cookbooks/',
  path: '/cookbooks/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesNewRoute = RecipesNewRouteImport.update({
  id: '/recipes/new',
  path: '/recipes/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesIdRoute = RecipesIdRouteImport.update({
  id: '/recipes/$id',
  path: '/recipes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileEditRoute = ProfileEditRouteImport.update({
  id: '/profile/edit',
  path: '/profile/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIdRoute = ProfileIdRouteImport.update({
  id: '/profile/$id',
  path: '/profile/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsIdRoute = LogsIdRouteImport.update({
  id: '/logs/$id',
  path: '/logs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CookbooksNewRoute = CookbooksNewRouteImport.update({
  id: '/cookbooks/new',
  path: '/cookbooks/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CookbooksIdRoute = CookbooksIdRouteImport.update({
  id: '/cookbooks/$id',
  path: '/cookbooks/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/auth/signin',
  path: '/auth/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesIdIndexRoute = RecipesIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RecipesIdRoute,
} as any)
const CookbooksIdIndexRoute = CookbooksIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CookbooksIdRoute,
} as any)
const RecipesIdEditRoute = RecipesIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => RecipesIdRoute,
} as any)
const CookbooksIdEditRoute = CookbooksIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => CookbooksIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/cookbooks/$id': typeof CookbooksIdRouteWithChildren
  '/cookbooks/new': typeof CookbooksNewRoute
  '/logs/$id': typeof LogsIdRoute
  '/profile/$id': typeof ProfileIdRoute
  '/profile/edit': typeof ProfileEditRoute
  '/recipes/$id': typeof RecipesIdRouteWithChildren
  '/recipes/new': typeof RecipesNewRoute
  '/cookbooks/': typeof CookbooksIndexRoute
  '/logs/': typeof LogsIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/recipes/': typeof RecipesIndexRoute
  '/cookbooks/$id/edit': typeof CookbooksIdEditRoute
  '/recipes/$id/edit': typeof RecipesIdEditRoute
  '/cookbooks/$id/': typeof CookbooksIdIndexRoute
  '/recipes/$id/': typeof RecipesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/cookbooks/new': typeof CookbooksNewRoute
  '/logs/$id': typeof LogsIdRoute
  '/profile/$id': typeof ProfileIdRoute
  '/profile/edit': typeof ProfileEditRoute
  '/recipes/new': typeof RecipesNewRoute
  '/cookbooks': typeof CookbooksIndexRoute
  '/logs': typeof LogsIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/recipes': typeof RecipesIndexRoute
  '/cookbooks/$id/edit': typeof CookbooksIdEditRoute
  '/recipes/$id/edit': typeof RecipesIdEditRoute
  '/cookbooks/$id': typeof CookbooksIdIndexRoute
  '/recipes/$id': typeof RecipesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/cookbooks/$id': typeof CookbooksIdRouteWithChildren
  '/cookbooks/new': typeof CookbooksNewRoute
  '/logs/$id': typeof LogsIdRoute
  '/profile/$id': typeof ProfileIdRoute
  '/profile/edit': typeof ProfileEditRoute
  '/recipes/$id': typeof RecipesIdRouteWithChildren
  '/recipes/new': typeof RecipesNewRoute
  '/cookbooks/': typeof CookbooksIndexRoute
  '/logs/': typeof LogsIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/recipes/': typeof RecipesIndexRoute
  '/cookbooks/$id/edit': typeof CookbooksIdEditRoute
  '/recipes/$id/edit': typeof RecipesIdEditRoute
  '/cookbooks/$id/': typeof CookbooksIdIndexRoute
  '/recipes/$id/': typeof RecipesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/explore'
    | '/auth/signin'
    | '/auth/signup'
    | '/cookbooks/$id'
    | '/cookbooks/new'
    | '/logs/$id'
    | '/profile/$id'
    | '/profile/edit'
    | '/recipes/$id'
    | '/recipes/new'
    | '/cookbooks/'
    | '/logs/'
    | '/profile/'
    | '/recipes/'
    | '/cookbooks/$id/edit'
    | '/recipes/$id/edit'
    | '/cookbooks/$id/'
    | '/recipes/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/explore'
    | '/auth/signin'
    | '/auth/signup'
    | '/cookbooks/new'
    | '/logs/$id'
    | '/profile/$id'
    | '/profile/edit'
    | '/recipes/new'
    | '/cookbooks'
    | '/logs'
    | '/profile'
    | '/recipes'
    | '/cookbooks/$id/edit'
    | '/recipes/$id/edit'
    | '/cookbooks/$id'
    | '/recipes/$id'
  id:
    | '__root__'
    | '/'
    | '/explore'
    | '/auth/signin'
    | '/auth/signup'
    | '/cookbooks/$id'
    | '/cookbooks/new'
    | '/logs/$id'
    | '/profile/$id'
    | '/profile/edit'
    | '/recipes/$id'
    | '/recipes/new'
    | '/cookbooks/'
    | '/logs/'
    | '/profile/'
    | '/recipes/'
    | '/cookbooks/$id/edit'
    | '/recipes/$id/edit'
    | '/cookbooks/$id/'
    | '/recipes/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExploreRoute: typeof ExploreRoute
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
  CookbooksIdRoute: typeof CookbooksIdRouteWithChildren
  CookbooksNewRoute: typeof CookbooksNewRoute
  LogsIdRoute: typeof LogsIdRoute
  ProfileIdRoute: typeof ProfileIdRoute
  ProfileEditRoute: typeof ProfileEditRoute
  RecipesIdRoute: typeof RecipesIdRouteWithChildren
  RecipesNewRoute: typeof RecipesNewRoute
  CookbooksIndexRoute: typeof CookbooksIndexRoute
  LogsIndexRoute: typeof LogsIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  RecipesIndexRoute: typeof RecipesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/': {
      id: '/recipes/'
      path: '/recipes'
      fullPath: '/recipes/'
      preLoaderRoute: typeof RecipesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs/': {
      id: '/logs/'
      path: '/logs'
      fullPath: '/logs/'
      preLoaderRoute: typeof LogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookbooks/': {
      id: '/cookbooks/'
      path: '/cookbooks'
      fullPath: '/cookbooks/'
      preLoaderRoute: typeof CookbooksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/new': {
      id: '/recipes/new'
      path: '/recipes/new'
      fullPath: '/recipes/new'
      preLoaderRoute: typeof RecipesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/$id': {
      id: '/recipes/$id'
      path: '/recipes/$id'
      fullPath: '/recipes/$id'
      preLoaderRoute: typeof RecipesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/edit': {
      id: '/profile/edit'
      path: '/profile/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof ProfileEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$id': {
      id: '/profile/$id'
      path: '/profile/$id'
      fullPath: '/profile/$id'
      preLoaderRoute: typeof ProfileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs/$id': {
      id: '/logs/$id'
      path: '/logs/$id'
      fullPath: '/logs/$id'
      preLoaderRoute: typeof LogsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookbooks/new': {
      id: '/cookbooks/new'
      path: '/cookbooks/new'
      fullPath: '/cookbooks/new'
      preLoaderRoute: typeof CookbooksNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookbooks/$id': {
      id: '/cookbooks/$id'
      path: '/cookbooks/$id'
      fullPath: '/cookbooks/$id'
      preLoaderRoute: typeof CookbooksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/auth/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/$id/': {
      id: '/recipes/$id/'
      path: '/'
      fullPath: '/recipes/$id/'
      preLoaderRoute: typeof RecipesIdIndexRouteImport
      parentRoute: typeof RecipesIdRoute
    }
    '/cookbooks/$id/': {
      id: '/cookbooks/$id/'
      path: '/'
      fullPath: '/cookbooks/$id/'
      preLoaderRoute: typeof CookbooksIdIndexRouteImport
      parentRoute: typeof CookbooksIdRoute
    }
    '/recipes/$id/edit': {
      id: '/recipes/$id/edit'
      path: '/edit'
      fullPath: '/recipes/$id/edit'
      preLoaderRoute: typeof RecipesIdEditRouteImport
      parentRoute: typeof RecipesIdRoute
    }
    '/cookbooks/$id/edit': {
      id: '/cookbooks/$id/edit'
      path: '/edit'
      fullPath: '/cookbooks/$id/edit'
      preLoaderRoute: typeof CookbooksIdEditRouteImport
      parentRoute: typeof CookbooksIdRoute
    }
  }
}

interface CookbooksIdRouteChildren {
  CookbooksIdEditRoute: typeof CookbooksIdEditRoute
  CookbooksIdIndexRoute: typeof CookbooksIdIndexRoute
}

const CookbooksIdRouteChildren: CookbooksIdRouteChildren = {
  CookbooksIdEditRoute: CookbooksIdEditRoute,
  CookbooksIdIndexRoute: CookbooksIdIndexRoute,
}

const CookbooksIdRouteWithChildren = CookbooksIdRoute._addFileChildren(
  CookbooksIdRouteChildren,
)

interface RecipesIdRouteChildren {
  RecipesIdEditRoute: typeof RecipesIdEditRoute
  RecipesIdIndexRoute: typeof RecipesIdIndexRoute
}

const RecipesIdRouteChildren: RecipesIdRouteChildren = {
  RecipesIdEditRoute: RecipesIdEditRoute,
  RecipesIdIndexRoute: RecipesIdIndexRoute,
}

const RecipesIdRouteWithChildren = RecipesIdRoute._addFileChildren(
  RecipesIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExploreRoute: ExploreRoute,
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
  CookbooksIdRoute: CookbooksIdRouteWithChildren,
  CookbooksNewRoute: CookbooksNewRoute,
  LogsIdRoute: LogsIdRoute,
  ProfileIdRoute: ProfileIdRoute,
  ProfileEditRoute: ProfileEditRoute,
  RecipesIdRoute: RecipesIdRouteWithChildren,
  RecipesNewRoute: RecipesNewRoute,
  CookbooksIndexRoute: CookbooksIndexRoute,
  LogsIndexRoute: LogsIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  RecipesIndexRoute: RecipesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
